name: Health check

on:
  schedule:
    - cron: "* * * * *" # why isnt this working

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-22xa.onrender.com
