name: Testing

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: context
        env:
          COMMIT_MESSAGE: ${{ contains(join(github.event.commits.*.message), "#skip")}}
        run: echo "$COMMIT_MESSAGE"
